list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_dc15a",	title = "SW_DC-15A" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_dc15s",	title = "SW_DC-15S" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_dc15sa",	title = "SW_DC-15 Side Arm" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_e5",	title = "SW_E-5" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_ee3",	title = "SW_EE-3" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_ihr",	title = "SW_Imperial Heavy Repeater" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_t21",	title = "SW_T-21" }  )
